### ISSUE TITLE
not working on firefox 43

### ISSUE THREAD

**Issue by chokopa15** [TRoskop/AdDefender#1]
thank you for your nice work
i want just you notify that is not working on Firefox 43 with adblock plus
(working perfectly on chrome)

keep up the good work

**Comment by TRoskop** [comment]
Hello chokopa15, thanks for your feedback.
That's realy weird. I just tried it again with AdBlockPlus (downloaded here: https://adblockplus.org/) on my Firefox 43.0: And it works. 
Are you using the default options? Probably you have changed the filter lists.
AdDefender is based on the most common list, EasyList (https://easylist-downloads.adblockplus.org/easylist.txt), and therefore if you have disabled it it might not work.

**Comment by chokopa15** [comment]
sorry for the delay
i tried to disable and enable some filtres
same
http://img15.hostingpics.net/pics/233466adblkstp.jpg

**Comment by rene-hermenau** [comment]
I confirm its not working on Firefox 43 (german) and not in Firefox ESR. I installed https://adblockplus.org/ and reproduced it. No error in console. The firefox 43 was fresh installed, no custom settings, all default settings. No other plugins are installed.

Chrome is working great.

**Comment by TRoskop** [comment]
Hallo @chokopa15 and @rene-hermenau,
I tried it again. And I was not able to reproduce the error.
When I enable AdBlockPlus, it successfully shows the warning message. On Chromium (not Chrome), as you also said, it works perfect. 
About my Browser: 43.0 - Mozilla Firefox for Ubuntu (running on Ubuntu 15.10; everything's up-to-date).

Note, the Download-Host https://easylist-downloads.adblockplus.org/easylist.txt seems to be offline currently. So it might be that your Lists are not up-to-date. My easylist version is from 28th december 2015 whereas yours, dear @chokopa15, is from the 25th december.

Could you try to use **uBlock Origin** for Firefox [https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/] on your machine. Without any custom settings please. 
On my Browser, this addon, which uses the same lists, leads AdDefender to show the warning message.

Thanks for your feedback. And a happy new year!

**Comment by chokopa15** [comment]
i confirm when i updated the easy list filter to 30/12, the script works now :)

**Comment by TRoskop** [comment]
Yeah, this is wonderful!
This means the easylist-server is online again.

**Comment by rene-hermenau** [comment]
@TRoskop ublock origin is working but adblockplus is still not working on my firefox. I also verified that the filter are updated.

However can you short summarize how your adblocker is working? Usually i do not have problems with understanding code but personally i am not using any adblocker, so It seems i lack some fundamentals here:)

I assume some element is part of the easylist.txt so it gets removed and the _AdDefenderValid() === false resulting in appearing of the red background colored notice.

Can you tell me the element name which should be filtered by uBlock origin andadblockplus? So i am able to debug this issue on my system.

**Comment by TRoskop** [comment]
The way it works is very simple:

It tries to load a second .js file [location: http://trserver1.site40.net/projects/AdDefender/acfp.js] which has a name the Adblocker knows as an ad-file and therefore blocks it.
But if this file cannot be loaded, the function "_AdDefenderValid()" is not implemented which leads the internal script to think a Blocker was found.
Only if the script thinks no blocker is there, it removes the correct element. Using the php-framework the exact name and class of this element changes so no "hide element by id" would work.
If the script cannot run (NoScript or blocked JS) or the script does not remove the element, the css-classes load the content after 1 second delay and shows it. 

Later the external script and its "_AdDefenderValid()" could check that the ads are shown successfully, but this is for the future...

Probably your filter removed the file name. I'll try later to change the file name to another one just to see if it solves it.

**Comment by TRoskop** [comment]
Hi!
So, I changed the name to another one which is in the filter-list. This *should* fix the issue.

**Comment by rene-hermenau** [comment]
It's working perfectly now:-) Thanks @TRoskop 

Just a simple and powerful solution which also works when js is disabled compared to other similar projects. I will recommend it.
