### ISSUE TITLE
Demo funktioniert nicht korrekt

### ISSUE THREAD

**Issue by Daijobou** [TRoskop/AdDefender#2]
Ich bin mal so frei und schreibe in Deutsch, wenn es in Ordnung ist. Ich habe mir mal kurz deine Demo angeschaut und mir ist aufgefallen, dass die id und die class, welche du per Zufall erzeugen willst, sich nicht nach jedem Seitenaufruf (F5) ändern. Siehe
~~~~~
<div class="qoN6xl538-g-" id="zogcklmOvJWT">
~~~~~
Desweiteren beginnt die class immer mit "q" und die id darin mit "z" in einem gemeinsamen div. Per Regex lässt sich das sicher simple rausfilter. Du solltest einfach auf "-" und Zahlen verzichten. Das macht es nicht sicherer. ids und class bestehen eher selten aus Zahlen und einem Bindestrich. Auch solltest du die Länge der Variable dynamisch gestalten und so lang müssen sie auch nicht sein. Auch das macht es nicht sicherer.

----

Auch dein HTML Kommentar ist vermutlich ein schöner Angriffspunkt um den kompletten Bereich dazwischen per Filter zu entfernen.

----

Ich würde in der Demo auch das riesige CSS stark einschränken. Diese Feinheiten kann man ruhig dem Webmaster überlassen und machen so den Code unnötig unübersichtlich. ;)

----

Wenn ich das richtig kurz überschaue, dann hoffst du das eine Datei vom Adblocker nicht geladen wird,
~~~~~
<script type="text/javascript" src="adwordstracking.js"></script>
~~~~~
und dadurch die Adblocker Mitteilung nicht entfernt wird. Der Ansatz ist denke ich der älteste den es gibt und wird dich hier nicht dauerhaft weiterbringen. Das selbe hatte ich vor Jahren gemacht und selbst meine kleine Seite landete dann scnell im Filter wo für meine Domain auf diese Datei einfach nicht geprüft wurde und damit war der Anti-Werbeblocker unwirksam. Um das zu umgehen hätte ich obige JS-Datei ständig im Namen ändern müssen.

**Comment by Daijobou** [comment]
Hier hast du zum Beispiel das selbe Prinzip wesentlich kürzer http://d3xt3r.com/anti-adblock nur das er es in der JS-Datei abhandelt und du außerhalb machst mit noch Zufallsnamen. Macht aber letztendlich keinen Unterschied, denn es reicht wie gesagt die Datei "adwordstracking.js" als Ausnahme in den Adblockfilter zu definieren, damit wir diese normal geladen und deine Abfrage unwirksam.

**Comment by TRoskop** [comment]
Hallo,

Woher wusstest du, dass ich deutscher bin?

Die Demo verwendet ein statisches HTML, nur das php Script kann Zufallszahlen und IDs liefern. Und auch das css etc. wird vom Script geliefert. 

Die . Js Datei soll später mit Funktionen ausgestattet werden, die prüfen, ob die Werbung geladen und angezeigt wurde. Also es basiert nicht nur auf dem Trick mit dem Namen. 

Das Projekt ist ja auch noch nicht fertig habe nur derzeit noch anderes um die Ohren. Freue mich aber immer auf Rückmeldung! 

Thomas
